/**
 * AI Service — ML-First Diet Plan Generation Pipeline
 *
 * Pipeline:
 *   1. Fetch member profile from MongoDB
 *   2. Fetch live prices from FoodPrice collection
 *   3. Call Python ML service → get structured meal plan
 *   4. Call Gemini API → add recipes, descriptions, cooking instructions
 *   5. Merge ML data + Gemini content → save to MongoDB
 *
 * Fallback: If ML service is down, Gemini generates the full plan.
 */

const { GoogleGenerativeAI } = require('@google/generative-ai');
const Member = require('../models/Member');
const DietPlan = require('../models/DietPlan');
const FoodPrice = require('../models/FoodPrice');
const { getMLRecommendation } = require('./mlService');

// Initialize Gemini keys support for basic rotation (comma-separated keys)
const geminiKeys = (process.env.GEMINI_API_KEY || '').split(',').map(k => k.trim()).filter(Boolean);
let currentGeminiKeyIndex = 0;

const getNextGenAI = () => {
    if (geminiKeys.length === 0) {
        throw new Error("GEMINI_API_KEY is not configured in the environment variables.");
    }
    const key = geminiKeys[currentGeminiKeyIndex];
    currentGeminiKeyIndex = (currentGeminiKeyIndex + 1) % geminiKeys.length;
    // Log masked key for debugging
    const maskedKey = key.substring(0, 4) + '...' + key.slice(-4);
    console.log(`🔑 Using Gemini API Key ${currentGeminiKeyIndex === 0 ? geminiKeys.length : currentGeminiKeyIndex}/${geminiKeys.length} (${maskedKey})`);
    return new GoogleGenerativeAI(key);
};

/**
 * Build a live prices dict from MongoDB for the ML service
 */
const getLivePrices = async () => {
    const foods = await FoodPrice.find({ isVerified: true });
    const priceDict = {};
    foods.forEach(food => {
        priceDict[food.foodId] = {
            pricePerGram: food.lowestPricePerGram || food.averagePricePerGram
        };
    });
    return priceDict;
};

/**
 * Call Gemini to format the ML recommendations into a polished plan
 * with recipes, descriptions, and cooking instructions.
 *
 * CRITICAL: Gemini CANNOT change the food items, portions, or macros.
 * It only adds the human-readable layer on top.
 */
const formatWithGemini = async (mlRecommendation, userProfile) => {
    const genAI = getNextGenAI();
    const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

    const prompt = `You are a professional nutritionist and recipe writer for SDFitness, a gym management app in Sri Lanka.

I have a 7-day meal plan generated by our ML model. The foods, portions, and macros are LOCKED — do NOT change them.

Your job is to add:
1. A short, appetizing name for each meal (e.g., "Protein Power Bowl")
2. A 1-sentence description
3. Step-by-step cooking instructions (3-5 steps max)
4. Prep time and cook time in minutes

USER PROFILE:
- Age: ${userProfile.age}, Gender: ${userProfile.gender}
- Goal: ${userProfile.goal}
- Dietary preferences: ${userProfile.dietary_preferences?.join(', ') || 'None'}

ML-GENERATED MEAL PLAN:
${JSON.stringify(mlRecommendation.days, null, 2)}

RESPOND IN VALID JSON ONLY. Use this exact structure:
{
  "days": [
    {
      "dayOfWeek": 0,
      "dayName": "Monday",
      "meals": [
        {
          "mealType": "breakfast",
          "name": "Meal Name Here",
          "description": "One sentence description",
          "instructions": ["Step 1", "Step 2", "Step 3"],
          "prepTime": 5,
          "cookTime": 10
        }
      ]
    }
  ]
}

RULES:
- DO NOT change food items, quantities, or macros
- Keep instructions practical for a Sri Lankan kitchen
- Use simple, accessible language
- Each meal name should be unique and appetizing
- Return ONLY the JSON, no markdown, no code blocks`;

    try {
        const result = await model.generateContent(prompt);
        const text = result.response.text();

        // Parse JSON from response (strip markdown code blocks if present)
        let jsonStr = text;
        const jsonMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/);
        if (jsonMatch) {
            jsonStr = jsonMatch[1];
        }

        const parsedGemini = JSON.parse(jsonStr.trim());
        console.log("Raw Gemini JSON:", JSON.stringify(parsedGemini, null, 2));
        return parsedGemini;
    } catch (error) {
        console.error('❌ Gemini formatting error:', error.message);
        return null;
    }
};

/**
 * Gemini-only fallback — generates entire plan without ML model
 */
const generateWithGeminiOnly = async (userProfile) => {
    const genAI = getNextGenAI();
    const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

    const prompt = `You are a professional nutritionist for SDFitness gym in Sri Lanka.

Generate a detailed 7-day meal plan for this user:
- Age: ${userProfile.age}, Weight: ${userProfile.weight_kg}kg, Height: ${userProfile.height_cm}cm
- Gender: ${userProfile.gender}
- Activity Level: ${userProfile.activity_level || 'moderately_active'}
- Goal: ${userProfile.goal}
- Budget: ${userProfile.diet_budget?.amount || 7000} ${userProfile.diet_budget?.currency || 'LKR'} per ${userProfile.diet_budget?.period || 'week'}
- Dietary preferences: ${userProfile.dietary_preferences?.join(', ') || 'None'}
- Allergies: ${userProfile.allergies?.join(', ') || 'None'}

Use foods commonly available in Sri Lankan supermarkets (Keells, Arpico).
Prices should be in LKR.

RESPOND IN VALID JSON ONLY with this structure:
{
  "targetCalories": 2000,
  "macroSplit": { "protein": { "grams": 100, "percentage": 30 }, "carbs": { "grams": 200, "percentage": 40 }, "fats": { "grams": 65, "percentage": 30 } },
  "days": [
    {
      "dayOfWeek": 0,
      "dayName": "Monday",
      "meals": [
        {
          "mealType": "breakfast",
          "name": "Meal Name",
          "items": [{ "food": "Food Name", "quantity": 150, "unit": "g" }],
          "calories": 400,
          "macros": { "protein": 25, "carbs": 40, "fats": 12, "fiber": 5 },
          "estimatedCost": { "amount": 250, "currency": "LKR" },
          "description": "One sentence",
          "instructions": ["Step 1", "Step 2"],
          "prepTime": 5,
          "cookTime": 10
        }
      ]
    }
  ]
}

Return ONLY valid JSON, no markdown, no code blocks.`;

    try {
        const result = await model.generateContent(prompt);
        const text = result.response.text();

        let jsonStr = text;
        const jsonMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/);
        if (jsonMatch) {
            jsonStr = jsonMatch[1];
        }

        return JSON.parse(jsonStr.trim());
    } catch (error) {
        console.error('❌ Gemini fallback error:', error.message);
        throw new Error('Both ML service and Gemini failed to generate diet plan');
    }
};

/**
 * MAIN: Generate a diet plan using the ML-first pipeline
 */
const generateDietPlan = async (memberId, formData = {}) => {
    // 1. Fetch member profile
    const member = await Member.findById(memberId);
    if (!member) throw new Error('Member not found');

    // Calculate age from dateOfBirth
    const age = Math.floor((Date.now() - new Date(member.dateOfBirth).getTime()) / (365.25 * 24 * 60 * 60 * 1000));

    // Convert comma-separated string back to array if needed for allergies
    let parsedAllergies = formData.allergies;
    if (typeof parsedAllergies === 'string') {
        parsedAllergies = parsedAllergies.split(',').map(a => a.trim()).filter(Boolean);
    }

    const userProfile = {
        age,
        weight_kg: member.currentWeight?.value || 70,
        height_cm: member.height?.value || 170,
        gender: member.gender === 'male' ? 'male' : 'female',
        activity_level: formData.activityLevel || member.activityLevel || 'moderately_active',
        goal: formData.goal || member.fitnessGoals?.[0] || 'general_fitness',
        dietary_preferences: formData.dietaryPreferences || member.dietaryPreferences || [],
        allergies: parsedAllergies || member.allergies || [],
        diet_budget: {
            amount: formData.budget || member.dietBudget?.amount || 7000,
            currency: 'LKR',
            period: 'weekly'
        }
    };

    // 2. Fetch live prices
    const livePrices = await getLivePrices();

    // 3. Try ML service first
    let mlResult = null;
    let generationMethod = 'ml_plus_gemini';

    const mlResponse = await getMLRecommendation(userProfile, livePrices);
    if (mlResponse.success) {
        mlResult = mlResponse.data;
        console.log(`✅ ML recommendation received (confidence: ${mlResult.aiMetadata.mlConfidenceScore})`);
    } else {
        console.warn(`⚠️  ML service failed: ${mlResponse.error}. Falling back to Gemini-only.`);
        generationMethod = 'gemini_only_fallback';
    }

    // 4. Generate the plan
    let planData;

    if (mlResult) {
        // ML-first: format with Gemini
        const geminiFormatted = await formatWithGemini(mlResult, userProfile);

        // Merge: ML structure + Gemini recipes
        planData = {
            targetCalories: mlResult.targetCalories,
            macroSplit: mlResult.macroSplit,
            days: mlResult.days.map((day, i) => {
                const geminiDay = geminiFormatted?.days?.find(d => d.dayOfWeek === day.dayOfWeek || d.dayName === day.dayName) || geminiFormatted?.days?.[i];
                return {
                    ...day,
                    meals: day.meals.map((meal) => {
                        const geminiMeal = geminiDay?.meals?.find(m => m.mealType === meal.mealType);
                        return {
                            ...meal,
                            name: geminiMeal?.name || `${meal.mealType.replace('_', ' ')} meal`,
                            description: geminiMeal?.description || '',
                            instructions: geminiMeal?.instructions || [],
                            prepTime: geminiMeal?.prepTime || 10,
                            cookTime: geminiMeal?.cookTime || 15
                        };
                    })
                };
            }),
            shoppingList: mlResult.shoppingList,
            aiMetadata: {
                ...mlResult.aiMetadata,
                generationMethod: 'ml_plus_gemini',
                gptModel: 'gemini-2.0-flash'
            }
        };
    } else {
        // Fallback: Gemini generates everything
        const geminiPlan = await generateWithGeminiOnly(userProfile);
        planData = {
            ...geminiPlan,
            shoppingList: { items: [], totalAtGeneration: 0, currentTotal: 0 },
            aiMetadata: {
                generationMethod: 'gemini_only_fallback',
                gptModel: 'gemini-2.0-flash',
                mlConfidenceScore: 0
            }
        };
    }

    // 5. Save to MongoDB
    const dietPlan = new DietPlan({
        memberId,
        planName: `${userProfile.goal.replace('_', ' ')} plan`,
        goal: userProfile.goal,
        targetCalories: planData.targetCalories,
        macroSplit: planData.macroSplit,
        budget: userProfile.diet_budget,
        days: planData.days,
        shoppingList: {
            ...planData.shoppingList,
            lastPriceUpdate: new Date(),
            priceChanged: false
        },
        aiMetadata: planData.aiMetadata,
        status: 'completed',
        preferences: {
            dietary: userProfile.dietary_preferences,
            allergies: userProfile.allergies,
            budget: userProfile.diet_budget.amount
        }
    });

    await dietPlan.save();
    console.log(`💾 Diet plan saved: ${dietPlan._id}`);

    return dietPlan;
};

module.exports = { generateDietPlan, getLivePrices, formatWithGemini };
