/**
 * AI Service — ML-First Diet Plan Generation Pipeline
 *
 * Pipeline:
 *   1. Fetch member profile from MongoDB
 *   2. Fetch live prices from FoodPrice collection
 *   3. Call Python ML service → get structured meal plan
 *   4. Call Gemini API → add recipes, descriptions, cooking instructions
 *   5. Merge ML data + Gemini content → save to MongoDB
 *
 * Fallback: If ML service is down, Gemini generates the full plan.
 */

const OpenAI = require('openai');
const Member = require('../models/Member');
const DietPlan = require('../models/DietPlan');
const getFoodPriceModel = require('../models/FoodPrice');
const { getMLRecommendation } = require('./mlService');

// Helper to get all keys from a comma-separated list
const getApiKeys = () => {
    const keys = process.env.NVIDIA_API_KEY || '';
    return keys.split(',').map(k => k.trim()).filter(k => k.length > 0);
};

// Model to use for formatting
const NVIDIA_MODEL = 'meta/llama-3.1-70b-instruct';

/**
 * Helper to call Nvidia with specific API key
 */
const callNvidia = async (messages, apiKey, temperature = 0.2) => {
    try {
        console.log(`[AI] Attempting Nvidia request with key: ${apiKey.substring(0, 10)}...`);
        const client = new OpenAI({
            apiKey: apiKey,
            baseURL: 'https://integrate.api.nvidia.com/v1'
        });

        const response = await client.chat.completions.create({
            model: NVIDIA_MODEL,
            messages,
            temperature,
            max_tokens: 4096,
            response_format: { type: 'json_object' }
        });

        console.log(`[AI] Nvidia response received successfully.`);
        return response;
    } catch (error) {
        console.error(`⚠️  Nvidia API failed: ${error.message}`);
        throw error;
    }
};

/**
 * Build a live prices dict from MongoDB for the ML service
 */
const getLivePrices = async () => {
    const FoodPrice = getFoodPriceModel();
    const foods = await FoodPrice.find({ isVerified: true });
    const priceDict = {};
    foods.forEach(food => {
        priceDict[food.foodId] = {
            pricePerGram: food.lowestPricePerGram || food.averagePricePerGram
        };
    });
    return priceDict;
};

/**
 * Call Nvidia AI to format a SINGLE day from the ML recommendation
 */
const formatDayWithNvidia = async (day, userProfile, apiKey) => {
    const prompt = `You are a professional nutritionist for SDFitness in Sri Lanka. 
I have a day of meals generated by our ML model. The foods, portions, and macros are LOCKED.

Add appetizing Sri Lankan inspired names (e.g. Dhal Curry, Pol Sambol, Fish Ambul Thiyal, Kottu, String Hoppers) where appropriate based on the ingredients, one-sentence descriptions, and AT LEAST 5 defined, actionable cooking instructions for each meal.
IMPORTANT FOR INSTRUCTIONS: Do NOT prefix the steps with "Step 1:", "Step 2:", etc. Just write the instructions clearly.
Also extract an 'essentialIngredients' array of spices, herbs, and staples needed to cook it (e.g., curry leaves, turmeric, pandan, coconut milk) that are not in the main ingredients. Make sure the instructions clearly mention when to use these essential ingredients.

USER PROFILE:
- Goal: ${userProfile.goal}
- Preferences: ${userProfile.dietary_preferences?.join(', ') || 'None'}

DAY TO FORMAT (${day.dayName}):
${JSON.stringify(day.meals, null, 2)}

RESPOND IN VALID JSON ONLY:
{
  "meals": [
    {
      "mealType": "breakfast",
      "name": "Kiribath with Lunu Miris",
      "description": "A classic Sri Lankan breakfast.",
      "essentialIngredients": ["2 cups coconut milk", "1 tsp turmeric", "6 curry leaves"],
      "instructions": ["Step 1...", "Step 2...", "Step 3...", "Step 4...", "Step 5..."],
      "prepTime": 10,
      "cookTime": 20
    }
  ]
}

Only return valid JSON. Do not include markdown code blocks.`;

    try {
        const response = await callNvidia([{ role: 'user', content: prompt }], apiKey);
        let text = response.choices[0].message.content.trim();
        if (text.startsWith('\`\`\`json')) {
            text = text.replace(/^\`\`\`json\n/, '').replace(/\n\`\`\`$/, '');
        }
        return JSON.parse(text);
    } catch (error) {
        console.error(`❌ Nvidia formatting error for ${day.dayName}:`, error.message);
        return null; // Return null so we can fallback to raw ML data
    }
};

/**
 * Nvidia-only fallback — generates entire plan without ML model
 */
const generateWithNvidiaOnly = async (userProfile) => {
    console.log(`[AI] Generating full 7-day plan (fallback mode)...`);
    const prompt = `Generate a 7-day Sri Lankan healthy meal plan in JSON for:
- Age: ${userProfile.age}, Weight: ${userProfile.weight_kg}kg
- Goal: ${userProfile.goal}
- Budget: ${userProfile.diet_budget?.amount || 7000} LKR/week

RESPOND IN VALID JSON ONLY:
{
  "targetCalories": 2000,
  "macroSplit": { "protein": { "grams": 100, "percentage": 30 }, "carbs": { "grams": 200, "percentage": 40 }, "fats": { "grams": 65, "percentage": 30 } },
  "days": [...]
}

Include items, calories, macros, cost, description and instructions for each meal.`;

    try {
        const keys = getApiKeys();
        const response = await callNvidia([{ role: 'user', content: prompt }], keys[0]);
        return JSON.parse(response.choices[0].message.content.trim());
    } catch (error) {
        console.error('❌ Nvidia fallback error:', error.message);
        throw new Error('Both ML service and Nvidia failed to generate diet plan');
    }
};

/**
 * MAIN: Generate a diet plan using the ML-first pipeline
 */
const generateDietPlan = async (memberId, shouldSave = true, overrides = {}) => {
    // 1. Fetch member profile
    const member = await Member.findById(memberId);
    if (!member) throw new Error('Member not found');

    // Calculate age from dateOfBirth (fallback to 25)
    let age = 25;
    if (member.dateOfBirth) {
        try {
            age = Math.floor((Date.now() - new Date(member.dateOfBirth).getTime()) / (365.25 * 24 * 60 * 60 * 1000));
            if (isNaN(age)) age = 25;
        } catch (e) {
            age = 25;
        }
    }

    const userProfile = {
        age,
        weight_kg: member.currentWeight?.value || 70,
        height_cm: member.height?.value || 170,
        gender: member.gender === 'male' ? 'male' : 'female',
        activity_level: overrides.activity_level || member.activityLevel || 'moderate',
        goal: overrides.goal || member.fitnessGoals?.[0] || 'maintenance',
        dietary_preferences: overrides.dietary_preferences || member.dietaryPreferences || [],
        allergies: overrides.allergies || member.allergies || [],
        diet_budget: overrides.diet_budget || member.dietBudget || { amount: 7000, currency: 'LKR', period: 'weekly' }
    };

    // 2. Fetch live prices
    const livePrices = await getLivePrices();

    // 3. Try ML service first
    let mlResult = null;
    let generationMethod = 'ml_plus_nvidia';

    const mlResponse = await getMLRecommendation(userProfile, livePrices);
    if (mlResponse.success) {
        mlResult = mlResponse.data;
        console.log(`✅ ML recommendation received (confidence: ${mlResult.aiMetadata.mlConfidenceScore})`);
    } else {
        console.warn(`⚠️  ML service failed: ${mlResponse.error}. Falling back to Nvidia-only.`);
        generationMethod = 'nvidia_only_fallback';
    }

    // 4. Generate the plan
    let planData;

    if (mlResult) {
        // ML-first: format with Nvidia (Parallel 4+3 Days)
        console.log(`[AI] Formatting recipes in parallel batches (7 days)...`);
        const processedDays = [];
        const keys = getApiKeys();

        if (keys.length === 0) {
            throw new Error("No NVIDIA API keys found in environment.");
        }

        // Helper to process a batch of days
        const processBatch = async (daysBatch, startIndex) => {
            return Promise.all(daysBatch.map(async (day, i) => {
                const keyIndex = (startIndex + i) % keys.length;
                const apiKey = keys[keyIndex];
                console.log(`[AI] Processing Day ${day.dayOfWeek} (${day.dayName}) with key idx ${keyIndex}...`);
                const formattedDayResult = await formatDayWithNvidia(day, userProfile, apiKey);
                return {
                    ...day,
                    meals: day.meals.map((meal, j) => {
                        const nvidiaMeal = formattedDayResult?.meals?.[j];
                        return {
                            ...meal,
                            name: nvidiaMeal?.name || `${meal.mealType} meal`,
                            description: nvidiaMeal?.description || '',
                            instructions: nvidiaMeal?.instructions || [],
                            essentialIngredients: nvidiaMeal?.essentialIngredients || [],
                            prepTime: nvidiaMeal?.prepTime || 10,
                            cookTime: nvidiaMeal?.cookTime || 15
                        };
                    })
                };
            }));
        };

        // Split days into batch 1 (Days 0-3) and batch 2 (Days 4-6)
        const batch1 = mlResult.days.slice(0, 4);
        const batch2 = mlResult.days.slice(4);

        console.log(`[AI] Starting Batch 1 (${batch1.length} days)...`);
        const processedBatch1 = await processBatch(batch1, 0);
        processedDays.push(...processedBatch1);

        if (batch2.length > 0) {
            console.log(`[AI] Starting Batch 2 (${batch2.length} days)...`);
            // Start using keys from where we left off, or reset to 0
            const processedBatch2 = await processBatch(batch2, batch1.length);
            processedDays.push(...processedBatch2);
        }

        console.log(`✅ All ${processedDays.length} days successfully formatted.`);

        // Aggregate essential ingredients for shopping list
        const essentialMap = new Map();
        processedDays.forEach(day => {
            day.meals.forEach(meal => {
                (meal.essentialIngredients || []).forEach(ingredient => {
                    // Normalize string
                    const normalized = ingredient.toLowerCase().trim();
                    if (!essentialMap.has(normalized)) {
                        essentialMap.set(normalized, {
                            foodId: `essential-${Date.now()}-${Math.random().toString(36).substring(7)}`,
                            name: ingredient,
                            quantity: 1,
                            unit: '',
                            category: 'Pantry & Spices',
                            priceAtGeneration: null,
                            currentPrice: null,
                            isEssential: true
                        });
                    }
                });
            });
        });

        const shoppingListItems = [
            ...(mlResult.shoppingList.items || []),
            ...Array.from(essentialMap.values())
        ];

        planData = {
            targetCalories: mlResult.targetCalories,
            macroSplit: mlResult.macroSplit,
            days: processedDays,
            shoppingList: {
                ...mlResult.shoppingList,
                items: shoppingListItems
            },
            aiMetadata: {
                ...mlResult.aiMetadata,
                generationMethod: 'ml_plus_nvidia',
                gptModel: NVIDIA_MODEL
            }
        };
    } else {
        // Fallback: Nvidia generates everything
        const nvidiaPlan = await generateWithNvidiaOnly(userProfile);
        planData = {
            ...nvidiaPlan,
            shoppingList: { items: [], totalAtGeneration: 0, currentTotal: 0 },
            aiMetadata: {
                generationMethod: 'nvidia_only_fallback',
                gptModel: NVIDIA_MODEL,
                mlConfidenceScore: 0
            }
        };
    }

    // 5. Save to MongoDB
    const dietPlan = new DietPlan({
        memberId,
        planName: `${userProfile.goal.replace(/[_-]/g, ' ')} plan`,
        targetCalories: planData.targetCalories,
        macroSplit: planData.macroSplit,
        budget: userProfile.diet_budget,
        days: planData.days,
        shoppingList: {
            ...planData.shoppingList,
            lastPriceUpdate: new Date(),
            priceChanged: false
        },
        aiMetadata: planData.aiMetadata,
        status: 'completed'
    });

    if (shouldSave) {
        await dietPlan.save();
        console.log(`💾 Diet plan saved: ${dietPlan._id}`);
    }

    return dietPlan;
};

module.exports = { generateDietPlan, getLivePrices, formatDayWithNvidia };
